import type { Metadata } from "next";
import { Playfair_Display, DM_Sans, Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/app/shared/Header";
import { supabaseAdmin } from "@/lib/supabase";
import IntakeForm from "@/components/app/form/IntakeForm";
import Card from "@/components/app/shared/Card";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const playfair = Playfair_Display({ 
  subsets: ["latin"], 
  weight: ["600", "700"],
  variable: "--font-playfair"
})
const dmSans = DM_Sans({ 
  subsets: ["latin"], 
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans"
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const {data: leads} = await supabaseAdmin.from('leads').select('*')
  
  return (
    <html lang="en">
      <head>
        <link rel="icon" type="image/svg+xml" href="/favicon.svg" />
      </head>
      <body
        className={`${playfair.variable} ${dmSans.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="min-h-screen bg-[#f4f4f0]" style={{ fontFamily: "'DM Sans', sans-serif" }}>
          <Header leads={leads ?? []} />
          <Card>
            {children} {/* Form or Dashboard components, wrapped within the card. */}
          </Card>
        </div>
        <ToastContainer position="top-center" autoClose={3000} />
      </body>
    </html>
  );
}
